### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by chinobing** [codingben/maple-fighters#75]
### Which project(s) are the source of the bug?

frontend

### Description

I deployed it with docker and `access forbidden by rule, client: 100.xxx.xx.xx,`.
Do i need to set up `EXTERNAL_IP ` for that?

### How To Reproduce

run by default command
```
docker-compose -f docker-compose.prod.yml up
```

### Expected Behavior

error

**Comment by codingben** [comment]
Hi @chinobing! you're using production yaml file which is not suitable locally. Please use `docker-compose.yml` to deploy it locally.
